import type { Metadata } from "next";
import "./globals.css";
import AppBar from "./components/AppBar";

export const metadata: Metadata = {
  title: "Test App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <AppBar />

        {children}
      </body>
    </html>
  );
}
